const express = require('express')
const cors = require('cors')
const app = express()
const bodyParser = require('body-parser')
require('dotenv').config()
app.use(bodyParser.urlencoded({ extended: false }))

const accountWorkerRouter = require('./src/routes/accountWorkers')
const accountRecruiterRouter = require('./src/routes/accountRecruiter')
const workerRouter = require('./src/routes/worker')
const recruiterRouter = require('./src/routes/recruiter')
const projectRouter = require('./src/routes/projects')
const hireRouter = require('./src/routes/hire')
const experienceRouter = require('./src/routes/experience')
const portofolioRouter = require('./src/routes/portfolio')
const skillRouter = require('./src/routes/skill')

app.use('/hire', hireRouter)
app.use('/skill', skillRouter)
app.use('/portofolio', portofolioRouter)
app.use('/experience', experienceRouter)
app.use('/project', projectRouter)
app.use('/account_worker', accountWorkerRouter)
app.use('/account_recruiter', accountRecruiterRouter)
app.use('/worker', workerRouter)
app.use('/recruiter', recruiterRouter)
app.use(cors())

app.use((request, response, next) => {
  console.log('cors activated')
  response.header('Access-Control-Allow-Origin', '*')
  response.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization')
  next()
})

app.listen(process.env.PORT, () => {
  console.log(`Server ${process.env.PORT} running!`)
})
