// const { request } = require('express')
const express = require('express')
const app = express()
const bodyParser = require('body-parser')
app.use(bodyParser.urlencoded({ extended: false }))

const accountWorkerRouter = require('./src/routes/accountWorkers')
const accountRecruiterRouter = require('./src/routes/accountRecruiter')
const workerRouter = require('./src/routes/worker')
const recruiterRouter = require('./src/routes/recruiter')
const projectRouter = require('./src/routes/projects')
const hireRouter = require('./src/routes/hire')
const experienceRouter = require('./src/routes/experience')
const portofolioRouter = require('./src/routes/portofolio')
const skillRouter = require('./src/routes/skill')

app.use('/hire', hireRouter)
app.use('/skill', skillRouter)
app.use('/portofolio', portofolioRouter)
app.use('/experience', experienceRouter)
app.use('/project', projectRouter)
app.use('/account_worker', accountWorkerRouter)
app.use('/account_recruiter', accountRecruiterRouter)
app.use('/worker', workerRouter)
app.use('/recruiter', recruiterRouter)

app.listen(8080, () => {
  console.log('Server 8080 running!')
})
